---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: {{ .Values.namespace.name }}
  labels:
    name: carts
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.carts.containerPort }}
  selector:
    name: carts
