---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: {{ .Values.namespace.name }}
  labels:
    name: front-end
spec:
  # type: NodePort
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    # nodePort: 30001
  selector:
    name: front-end
