---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: {{ .Values.namespace.name }}
  labels:
    name: orders
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.orders.containerPort }}
  selector:
    name: orders
