---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: {{ .Values.namespace.name }}
  labels:
    name: user-db
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: user-db
